
name: Deploy Techninxa

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore techninxa/techninxa.csproj

      - name: Build
        run: dotnet build techninxa/techninxa.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish techninxa/techninxa.csproj --configuration Release --output ./publish --no-build

      - name: Deploy to SolidCP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_PATH }}
          local-dir: ./publish/